### ISSUE TITLE
Sprint Swag Preparations

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#12]
@stephwright is 2018 Swag Queen! ❤️ 

- [x] Determine this year's swag-- let's make a cheap but varied packet of goodies for site hosts. 
- [x] Order Swag (receive by March 15)
- [x] Copy and update Swag Request form 

Possibilities for 2018 swag:
- Sprint Fox Stickers
- Mozilla Stickers?
- Any leftover "Web For All" stickers from MozFest, or reprints of that design?
- Small number (10-15) pre-printed flyers or postcards for site promo (use web graphics, leave space for address/contact/hours)? << especially useful for those in Africa/India who don't have printing capabilities

Please discuss and document progress by commenting on this issue. 😸

**Comment by stephwright** [comment]
Would like everything to be flat and light for mailing purposes, particularly since so many are in far flung places.... so stickers and other printable materials

Yes to Sprint Fox stickers, already have a template in Sticker Mule
Yes to Mozilla stickers, also have template ready in Sticker Mule
@acabunoc has reached out to rizki who manages reps swag to see what other options are.
For the site host registration, can we ask how many ppl they EXPECT (not just how many seats they have).  are there any other stickers that y'all can think of we might want to include? 

Do we want a hex Global Sprint sticker?
I have a query to the brand folks about what our "wordmark"/"logo" can be for GS

Here are last year's printed fliers... we will need to update for dates... we can either update to include date in the printed part, or leave the date open so we can use the same templates every year:

Global Sprint Site Announcement ([8.5” x 11” PDF](https://github.com/MozillaFoundation/Design/files/1033127/global-sprint-editable-8p5x11.pdf)) ([11” x 17” PDF](https://github.com/MozillaFoundation/Design/files/1033126/global-sprint-editable-11x17.pdf))
    Participation Guidelines ([8.5” x 11” PDF](https://github.com/MozillaFoundation/Design/files/1033129/participation-guidelines-8p5x11.pdf)) ([11” x 17” PDF](https://github.com/MozillaFoundation/Design/files/1033128/participation-guildelines-11x17.pdf))
    What is Mozilla? ([8.5” x 11” PDF](https://github.com/MozillaFoundation/Design/files/1033130/what-is-mozilla-8p5x11.pdf)) ([11” x 17” PDF](https://github.com/MozillaFoundation/Design/files/1033131/what-is-mozilla-11x17.pdf))

**Comment by stephwright** [comment]
We've got a wordmark/logo for GS but going to nix hex sticker for this year.  
For postage purchases going to stick to stickers and printed materials.
Current plan:
- Sprint Fox
- Mozilla
- Web for All
--- stickers from sponsors???? what do you think @Saallen @zee-moz 

Will send to first 75 site hosts.  
Will wait until closer to close of registration before sending.
Trying to figure out a good "distribution network" for shipping these out so I don't have to pay US postage to far flung places.  Current thought is to have Sticker Mule ship stickers directly to a designated sender in:
    Canada
    Africa
    UK
    Europe
    US - this will be me :)

**Comment by zee-moz** [comment]
Closing this "Preparations" issue for now, as we're well on the way! :)
