### ISSUE TITLE
Review of 2017 Site Content and Materials 

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#5]
[The 2017 site is here](https://mozilla.github.io/global-sprint/)
[The planning materials (wrangler guides, etc, created last year for Hub staff) are here](https://github.com/MozillaFoundation/2017-global-sprint-planning)
**Deadline for review: 2/7 if possible.**

Pls review with the following questions in mind:

- What's not clear? 
- What's hard to find? 
- What could be better organized? 
- What could be removed/edited down? 
- What might be missing? 
- How can the site better convey the experiences/opportunities of the Sprint
- How can the materials appeal to or welcome to broader audiences?

We got the following feedback in our debrief:
- “there was a lot of great info on the website - I heard feedback from a few people that it was hard to navigate through all of it, especailly since they were usually looking for something specific (rather than 'for project leads', 'for site hosts', etc) << what were the specific things they needed? - usually site or project list
- “Perhaps develop a webpage that's more closely linked to the Network site or Mozilla.org -- something with similar branding and language”
- “I think it will help to create user scenarios for the sprint next time - speaking to the points below about including more moco staff and non-digital people/projects - we could prepare stories of how different types of people might benefit...ex:
_Dome, Kenya. Software developer working on XXXXX wants to prototype......
Judy, Pune India. Teacher wants to practice using github so she can use it in the classroom....
Betty, farm owner in Rwanda wants help on a new website to advertise her products…”_

**Please add additional feedback as a comment on this issue**

**Comment by edrushka** [comment]
A few suggestions:
1) Simplify and clarify the description at the top of the site. E.g.:
Mozilla’s Global Sprint is a fun, two-day event to build projects for a healthy Internet. Collaborate online or in person with a diverse network of scientists, educators, artists, engineers, and others by contributing your skills and ideas to a project of your choice.

2) Reduce CTAs and be consistent with terms. 'Get your tickets' 'Join Us' and 'Register' are used interchangeably. I'd stick with 'Register'.

3) Add a 'What to Expect' section as the last item in the left column that explains what actually happens on the days of the sprint for both virtual and in-person contributors.

4) Add 'Sites list' as one of the drop down items under 'For Site Hosts' or 'For Participants' in the left column, since that's something people are searching for.

5) On the Projects page, there isn't an explanation of what a featured project is. Also, consider rolling the 'extra credit' items into the 'featured' requirements. The page layout makes it feel like there are 3 tiers of projects.

6) On Participants/Project Leads/Site Hosts pages, remove the "suggest changes" link at the top of each page. There's already a link at the bottom and it feels visually (and conceptually) disruptive at the top.
